// Deterministic generator for TRACEABILITY.md.
//
// Per book §4.4 (Final Outputs), every generated project ships with a
// traceability document mapping:
//   OPM objects   → database entities and classes
//   OPM processes → API endpoints and service logic
//   OPM states    → state fields and transition logic
//
// We generate this from the OPM IR + system spec rather than asking the LLM,
// so the deliverable is always present and exact (book §8.2 mandates 100%
// Traceability Completeness — we cannot rely on the model getting it right).

type OpmObject  = { id: string; name?: string; states?: string[] };
type OpmProcess = { id: string; name?: string };
type OpmLink    = { id: string; type?: string; from?: string; to?: string; via?: string };
type OpmModel   = {
    objects?:   OpmObject[];
    processes?: OpmProcess[];
    links?:     OpmLink[];
};

type SpecEntity   = { name?: string; source?: string };
type SpecEndpoint = { method?: string; path?: string; source?: string; op?: string; transition?: string };
type SystemSpec   = {
    domainModel?: { entities?:  SpecEntity[] };
    api?:         { endpoints?: SpecEndpoint[] };
};

function asOpm(x: unknown): OpmModel {
    return (x && typeof x === "object" ? x : {}) as OpmModel;
}
function asSpec(x: unknown): SystemSpec {
    return (x && typeof x === "object" ? x : {}) as SystemSpec;
}

export function generateTraceabilityMd(opm: unknown, spec: unknown): string {
    const o = asOpm(opm);
    const s = asSpec(spec);

    const objects   = o.objects   ?? [];
    const processes = o.processes ?? [];
    const links     = o.links     ?? [];

    const entities  = s.domainModel?.entities ?? [];
    const endpoints = s.api?.endpoints        ?? [];

    const entityForObject = (id: string): string =>
        entities.find((e) => e.source === id)?.name ?? "—";

    const endpointForProcess = (id: string): string => {
        const ep = endpoints.find((e) => e.source === id);
        if (!ep) return "—";
        return `\`${ep.method ?? "?"} ${ep.path ?? "?"}\`${ep.transition ? ` (${ep.transition})` : ""}`;
    };

    const lines: string[] = [];
    lines.push("# Traceability Report");
    lines.push("");
    lines.push("> Auto-generated from the OPM diagram by the OPM2Code pipeline.");
    lines.push("> Every OPM element is mapped to a concrete code artifact.");
    lines.push("> Per the capstone book §4.4 and §8.2, this file is mandatory.");
    lines.push("");

    lines.push(`Total elements: **${objects.length} objects · ${processes.length} processes · ${links.length} links**`);
    lines.push("");

    lines.push("## Objects → Database Entities");
    lines.push("");
    lines.push("| OPM ID | OPM Name | DB Entity |");
    lines.push("|---|---|---|");
    for (const obj of objects) {
        lines.push(`| \`${obj.id}\` | ${obj.name ?? "—"} | ${entityForObject(obj.id)} |`);
    }
    lines.push("");

    lines.push("## Processes → API Endpoints");
    lines.push("");
    lines.push("| OPM ID | OPM Name | Endpoint |");
    lines.push("|---|---|---|");
    for (const p of processes) {
        lines.push(`| \`${p.id}\` | ${p.name ?? "—"} | ${endpointForProcess(p.id)} |`);
    }
    lines.push("");

    lines.push("## States → State Fields & Transitions");
    lines.push("");
    const objectsWithStates = objects.filter((o) => Array.isArray(o.states) && o.states!.length > 0);
    if (objectsWithStates.length === 0) {
        lines.push("_No state-bearing objects in this model._");
    } else {
        lines.push("| Object | States | Implementation |");
        lines.push("|---|---|---|");
        for (const obj of objectsWithStates) {
            const ent = entityForObject(obj.id);
            const states = (obj.states ?? []).map((s) => `\`${s}\``).join(", ");
            lines.push(`| \`${obj.id}\` ${obj.name ?? ""} | ${states} | enum field on entity \`${ent}\` |`);
        }
    }
    lines.push("");

    lines.push("## Links → Software Constructs");
    lines.push("");
    if (links.length === 0) {
        lines.push("_No links in this model._");
    } else {
        lines.push("| OPM ID | Type | From → To | Implementation Hint |");
        lines.push("|---|---|---|---|");
        for (const l of links) {
            const impl = mapLinkType(l.type);
            const arrow = `${l.from ?? "?"} → ${l.to ?? "?"}${l.via ? ` (via ${l.via})` : ""}`;
            lines.push(`| \`${l.id}\` | ${l.type ?? "?"} | ${arrow} | ${impl} |`);
        }
    }
    lines.push("");

    lines.push("---");
    lines.push("");
    lines.push("_Generated by OPM2Code (capstone milestone). Do not edit by hand — re-run the pipeline to regenerate._");
    lines.push("");

    return lines.join("\n");
}

function mapLinkType(t: string | undefined): string {
    switch ((t ?? "").toLowerCase()) {
        case "agent":          return "authenticated principal / authorization context";
        case "instrument":     return "read-only dependency injected into endpoint";
        case "consumption":    return "destroyed / transitioned irreversibly when process runs";
        case "result":         return "process creates this entity (POST endpoint)";
        case "effect":         return "process mutates this entity (PUT/PATCH endpoint)";
        case "condition":      return "precondition guard on endpoint";
        case "invocation":     return "process triggers another process";
        case "event":          return "external event handler";
        case "aggregation":    return "one-to-many; FK from part → whole";
        case "exhibition":     return "attribute / characteristic of parent";
        case "generalization": return "inheritance / discriminator column";
        case "instantiation":  return "factory / class instance";
        case "state-change":   return "transition endpoint with 409 guard from wrong source state";
        default:               return "—";
    }
}
