// Tier 4 of the Testing Agent — acceptance testing + code review.
//
// An LLM independently derives ~10 functional acceptance tests + 5 code-review
// points from the generated repository. Operates on the IN-MEMORY artifact
// (no disk needed). Skips gracefully (returns empty) when Gemini is unavailable,
// so the deterministic tiers and the unit tests still run offline.

import { askJson, isGeminiConfigured } from "@/opm/pipeline/llm/gemini";
import type { FileSpec } from "./types";
import type { QaAcceptanceTest, QaReviewPoint } from "../infra/types";

function isTextFile(rel: string): boolean {
    return /\.(py|ts|tsx|js|jsx|json|md|ya?ml|toml|txt|html|css|sh|env|cfg|ini)$/i.test(rel)
        || /(^|\/)(Dockerfile|requirements\.txt|\.gitignore|\.env\.example)$/i.test(rel);
}

// Token-bounded snapshot of the repo for the reviewer.
function repoDigest(files: FileSpec[]): string {
    const blocks: string[] = [];
    let budget = 400_000; // total characters we'll send (Gemini holds the whole repo easily)

    for (const file of files) {
        // Skip non-text (binary) files.
        if (!isTextFile(file.path)) {
            continue;
        }
        // Stop once we've used up the character budget.
        if (budget <= 0) {
            break;
        }

        // Cap a single huge file so one file can't eat the whole budget.
        let content = file.content;
        if (content.length > 100_000) {
            content = content.slice(0, 100_000) + "\n# <-- file truncated for review only -->";
        }

        // Wrap it: a header line, the content, then a trailing newline.
        const block = `===FILE: ${file.path}===\n${content}\n`;
        blocks.push(block);
        budget = budget - block.length;
    }

    return blocks.join("\n");
}

const QA_PROMPT = `
You are an Automated QA Engineer & Code Reviewer. You independently evaluate the
repository below (generated by another agent). You have no prebuilt test suite —
derive everything from the manufactured code and its logical structure. You do
NOT run a test runner; you reason over the code.

Return STRICT JSON with exactly this shape (no prose, no fences):
{
  "acceptanceTests": [   // EXACTLY 10 high-level functional / integration tests
    { "objective": "...", "input": "...", "expected": "...", "status": "pass" | "fail" }
  ],
  "codeReview": [        // EXACTLY 5 most critical points, in this priority order:
    //   1 Security, 2 Architecture, 3 Performance, 4 Error Handling, 5 Readability
    { "category": "Security" | "Architecture" | "Performance" | "Error Handling" | "Readability",
      "file": "path", "context": "function/line area", "problem": "...", "suggestion": "..." }
  ]
}
Acceptance tests target end-to-end behavior the system actually implements: auth
flows, primary data ingestion, state mutations, core process execution. Set
status to "fail" when the code cannot plausibly satisfy the test (missing
endpoint, broken wiring, unhandled state). Output ONLY the JSON object.
`.trim();

type AcceptanceResult = { acceptanceTests: QaAcceptanceTest[]; codeReview: QaReviewPoint[] };

// The "nothing to report" result — used when QA is unavailable or fails.
function emptyResult(): AcceptanceResult {
    return { acceptanceTests: [], codeReview: [] };
}

// Run the acceptance review. Returns empty lists if Gemini is not configured or
// the call fails — a QA hiccup must never wrongly block the loop.
export async function runAcceptanceReview(files: FileSpec[]): Promise<AcceptanceResult> {
    // 1. No API key → skip this tier (the deterministic checks still run).
    if (!isGeminiConfigured()) {
        return emptyResult();
    }

    try {
        // 2. Pack the repo into one text block and ask the LLM to review it.
        const digest = repoDigest(files); //files =(array of {path, content}
        const prompt = `${QA_PROMPT}\n\n## REPOSITORY\n${digest}`;
        const res = await askJson<Partial<AcceptanceResult>>(prompt);

        // 3. Keep at most 10 tests and 5 review points; default to empty lists.
        let acceptanceTests: QaAcceptanceTest[] = [];
        if (res && Array.isArray(res.acceptanceTests)) {
            acceptanceTests = res.acceptanceTests.slice(0, 10);
        }

        let codeReview: QaReviewPoint[] = [];
        if (res && Array.isArray(res.codeReview)) {
            codeReview = res.codeReview.slice(0, 5);
        }

        return { acceptanceTests, codeReview };
    } catch (e) {
        // 4. A QA hiccup must never block the loop — log and return empty.
        console.warn("[testing-agent] acceptance review skipped:", (e as Error).message);
        return emptyResult();
    }
}
